import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
DATABASE_USERNAME = os.getenv("DATABASE_USERNAME")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
API_KEY = os.getenv("API_KEY")
NINJAS_API_KEY = os.getenv("NINJAS_API_KEY")
